
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tubi_
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Participate = new javax.swing.JButton();
        Unparticipate = new javax.swing.JButton();
        ShowActivity = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ShowUser = new javax.swing.JButton();
        ShowLocation = new javax.swing.JButton();
        ShowTime = new javax.swing.JButton();
        chooseActivity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        Participate.setText("Participate");
        Participate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParticipateActionPerformed(evt);
            }
        });

        Unparticipate.setText("Unparticipate");
        Unparticipate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnparticipateActionPerformed(evt);
            }
        });

        ShowActivity.setText("Show Activity Table");
        ShowActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActivityActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ActivityID", "ActivityName", "ActivityType", "Participants", "Null"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                             WEEKLY ACTIVITIES DATABASE");

        ShowUser.setText("Show User Table");
        ShowUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowUserActionPerformed(evt);
            }
        });

        ShowLocation.setText("Show Location Table");
        ShowLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowLocationActionPerformed(evt);
            }
        });

        ShowTime.setText("Show Time Table");
        ShowTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTimeActionPerformed(evt);
            }
        });

        chooseActivity.setForeground(new java.awt.Color(153, 153, 153));
        chooseActivity.setText("Choose an Activity ID");
        chooseActivity.setToolTipText("");
        chooseActivity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chooseActivityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                chooseActivityFocusLost(evt);
            }
        });
        chooseActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActivityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Participate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Unparticipate))
                            .addComponent(chooseActivity))))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Participate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Unparticipate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseActivity))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnparticipateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnparticipateActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/activitiesdb","root","18070006042n");
            
            Statement st = con.createStatement();
            String sql = "UPDATE Activity SET Participants = Participants - 1 WHERE ActivityID = " + chooseActivity.getText();
            int rs = st.executeUpdate(sql);
                     
            con.close();
            chooseActivity.setText("Choose an Activity ID");
        }
        catch(Exception e){
            System.out.println(e.getMessage());
           
        }
    }//GEN-LAST:event_UnparticipateActionPerformed

    private void ShowActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActivityActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/activitiesdb","root","18070006042n");
            
            Statement st = con.createStatement();
            String sql = "select * from activity";
            ResultSet rs = st.executeQuery(sql);
            
            JTableHeader th = jTable1.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            TableColumn tc = tcm.getColumn(0);
            tc.setHeaderValue( "ActivityID" );  
            tc = tcm.getColumn(1);
            tc.setHeaderValue( "ActivityName" );  
            tc = tcm.getColumn(2);
            tc.setHeaderValue( "ActivityType" );  
            tc = tcm.getColumn(3);
            tc.setHeaderValue( "Participants" );  
            tc = tcm.getColumn(4);
            tc.setHeaderValue( " " );  
            th.repaint();
            
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.setRowCount(0);
            
            while(rs.next()){
                String ActivityID   = String.valueOf(rs.getInt("ActivityID"));
                String ActivityName = rs.getString("ActivityName");
                String ActivityType = rs.getString("ActivityType");
                String Participants  = String.valueOf(rs.getInt("Participants"));
                
                String tbData[] = {ActivityID,ActivityName,ActivityType,Participants};
                tblModel.addRow(tbData);
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());   
        }
    }//GEN-LAST:event_ShowActivityActionPerformed

    private void ParticipateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParticipateActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/activitiesdb","root","18070006042n");
            
            Statement st = con.createStatement();
            String sql = "UPDATE Activity SET Participants = Participants + 1 WHERE ActivityID = " + chooseActivity.getText();
            int rs = st.executeUpdate(sql);
                     
            con.close();
            chooseActivity.setText("Choose an Activity ID");
        }
        catch(Exception e){
            System.out.println(e.getMessage());
           
        }
    }//GEN-LAST:event_ParticipateActionPerformed

    private void ShowUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowUserActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/activitiesdb","root","18070006042n");
            
            Statement st = con.createStatement();
            String sql = "select * from user";
            ResultSet rs = st.executeQuery(sql);
            
             JTableHeader th = jTable1.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            TableColumn tc = tcm.getColumn(0);
            tc.setHeaderValue( "UserID" );  
            tc = tcm.getColumn(1);
            tc.setHeaderValue( "UserName" );  
            tc = tcm.getColumn(2);
            tc.setHeaderValue( "UserSurname" );  
            tc = tcm.getColumn(3);
            tc.setHeaderValue( "Birthdate" );  
            tc = tcm.getColumn(4);
            tc.setHeaderValue( "UserPref" );  
            th.repaint();
            
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.setRowCount(0);
            
            while(rs.next()){
                String UserID = String.valueOf(rs.getInt("UserID"));
                String UserName = rs.getString("UserName");
                String UserSurname = rs.getString("UserSurname");
                String Birthdate = rs.getString("Birthdate");
                String UserPref = rs.getString("UserPref");
                
                
                String tbData[] = {UserID,UserName,UserSurname,Birthdate,UserPref};
                tblModel.addRow(tbData);
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
           
        }
    }//GEN-LAST:event_ShowUserActionPerformed

    private void ShowLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowLocationActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/activitiesdb","root","18070006042n");
            
            Statement st = con.createStatement();
            String sql = "select * from location";
            ResultSet rs = st.executeQuery(sql);
            
             JTableHeader th = jTable1.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            TableColumn tc = tcm.getColumn(0);
            tc.setHeaderValue( "LocationID" );  
            tc = tcm.getColumn(1);
            tc.setHeaderValue( "Adress" );  
            tc = tcm.getColumn(2);
            tc.setHeaderValue( "Name" );  
            tc = tcm.getColumn(3);
            tc.setHeaderValue( "Capacity" );  
            tc = tcm.getColumn(4);
            tc.setHeaderValue( "Description" );  
            th.repaint();
            
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.setRowCount(0);
            
            while(rs.next()){
                String LocationID = String.valueOf(rs.getInt("LocationID"));
                String Adress = rs.getString("Adress");
                String Name = rs.getString("Name");
                String Capacity = String.valueOf(rs.getInt("Capacity"));
                String Description = rs.getString("Description");
                
                
                String tbData[] = {LocationID,Adress,Name,Capacity,Description};
                tblModel.addRow(tbData);
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());  
        }       
    }//GEN-LAST:event_ShowLocationActionPerformed

    private void ShowTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTimeActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/activitiesdb","root","18070006042n");
            
            Statement st = con.createStatement();
            String sql = "select * from time";
            ResultSet rs = st.executeQuery(sql);
            
             JTableHeader th = jTable1.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            TableColumn tc = tcm.getColumn(0);
            tc.setHeaderValue( "TimeID" );  
            tc = tcm.getColumn(1);
            tc.setHeaderValue( "StartDate" );  
            tc = tcm.getColumn(2);
            tc.setHeaderValue( "EndDate" );  
            tc = tcm.getColumn(3);
            tc.setHeaderValue( "Length" );  
            tc = tcm.getColumn(4);
            tc.setHeaderValue( " " );  
            th.repaint();
            
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.setRowCount(0);
            
            while(rs.next()){
                String TimeID = String.valueOf(rs.getInt("TimeID"));
                String StartDate = rs.getString("StartDate");
                String EndDate = rs.getString("EndDate");
                String Length = String.valueOf(rs.getInt("Length"));
                                          
                String tbData[] = {TimeID,StartDate,EndDate ,Length};
                tblModel.addRow(tbData);
            }
            con.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
           
        }
    }//GEN-LAST:event_ShowTimeActionPerformed

    private void chooseActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseActivityActionPerformed

    private void chooseActivityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chooseActivityFocusGained
       if(chooseActivity.getText().equals("Choose an Activity ID")){
           
           chooseActivity.setText("");
           chooseActivity.setForeground(new Color(153,153,153));
           
       }
    }//GEN-LAST:event_chooseActivityFocusGained

    private void chooseActivityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chooseActivityFocusLost
        if(chooseActivity.getText().equals("")){
           
           chooseActivity.setText("Choose an Activity ID");
           chooseActivity.setForeground(new Color(153,153,153));
           
       }
    }//GEN-LAST:event_chooseActivityFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Participate;
    private javax.swing.JButton ShowActivity;
    private javax.swing.JButton ShowLocation;
    private javax.swing.JButton ShowTime;
    private javax.swing.JButton ShowUser;
    private javax.swing.JButton Unparticipate;
    private javax.swing.JTextField chooseActivity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
